add option for extended metapkg dir

diff --git a/upk b/upk
--- a/upk
+++ b/upk
@@ -2,6 +2,7 @@
 
 self_dir=$(dirname $(realpath ${BASH_SOURCE[0]}))
 source ${self_dir}/includes/const.in
+[[ -f ${data_dir}/upk.in ]] && source ${data_dir}/upk.in
 
 get_help() {
     printf "Usage: $(basename ${0}) <action> [app_id]\n"
@@ -14,43 +15,30 @@ get_help() {
     printf "   -h|--help\n"
 }
 
-trim_pkg_id() {
-    echo "${1//\//}" # remove slash
-}
-
 get_metapkg_dir() {
     local pkg_id="$1"
     test_var pkg_id ${pkg_id}
-    local dir=${self_dir}/metapkgs/${pkg_id}
-    [[ -d $dir ]] || dir=${data_dir}/${pkg_id}
-    [[ -d $dir ]] && echo $dir || errf "==> metapkg not found: $pkg_id"
-}
-
-get_confirmation() {
-    local sub_cmd="$1"
-    local skip_flag="$2"
-    shift && shift
-    local pkg_ids=("$@")
-    local confirmation=
-    if [[ "$skip_flag" != "-y" ]]; then
-        printf "Selected packages:\n"
-        for id in "${pkg_ids[@]}"; do
-            printf " $id"
-        done
-        printf "\n"
-        read -r -p "${sub_cmd^} packages? [y/N]: " confirmation
-    else
-        confirmation=y
+    local pkg_dir=
+    local test_dir=
+    if [[ -n "$UPK_METAPKG_DIR" && -d $UPK_METAPKG_DIR ]]; then
+        test_dir=${UPK_METAPKG_DIR}/${pkg_id}
+        [[ -d $test_dir ]] && pkg_dir=$test_dir
     fi
-    [[ "${confirmation}" =~ ^[yY]$ ]] || exit 1
+    if [[ ! -d $pkg_dir ]]; then
+        test_dir=${self_dir}/metapkgs/${pkg_id}
+        [[ -d $test_dir ]] && pkg_dir=$test_dir
+    fi
+    [[ -d $pkg_dir ]] && echo $pkg_dir || errf "==> metapkg not found: $pkg_id"
 }
 
 list_metapkgs() {
     local ids1=
     local ids2=
     local pkg_ids=
-    mapfile -t ids1 < <(ls -1 ${self_dir}/metapkgs/)
-    mapfile -t ids2 < <(ls -1 ${data_dir}/metapkgs/)
+    if [[ -n "$UPK_METAPKG_DIR" && -d $UPK_METAPKG_DIR ]]; then
+        mapfile -t ids1 < <(ls -1 ${UPK_METAPKG_DIR}/)
+    fi
+    mapfile -t ids2 < <(ls -1 ${self_dir}/metapkgs/)
     mapfile -t pkg_ids < <(printf "%s\n" "${ids1[@]}" "${ids2[@]}" | sort -u)
     local max_len=0
     local curr_len=0
@@ -75,6 +63,25 @@ clean_cache() {
         rm -rf ${cache_dir}/*
         echo "==> cleaned $(tilde_path $cache_dir)/"
     fi
+}
+
+get_confirmation() {
+    local sub_cmd="$1"
+    local skip_flag="$2"
+    shift && shift
+    local pkg_ids=("$@")
+    local confirmation=
+    if [[ "$skip_flag" != "-y" ]]; then
+        printf "Selected packages:\n"
+        for id in "${pkg_ids[@]}"; do
+            printf " $id"
+        done
+        printf "\n"
+        read -r -p "${sub_cmd^} packages? [y/N]: " confirmation
+    else
+        confirmation=y
+    fi
+    [[ "${confirmation}" =~ ^[yY]$ ]] || exit 1
 }
 
 update_installed() {
@@ -115,7 +122,7 @@ case "${1}" in
         pkg_ids=()
         pkg_scripts=()
         for arg in "$@"; do
-            arg=$(trim_pkg_id "$arg")
+            arg=${arg%/}
             if [[ "$arg" == "-y" ]]; then
                 skip_confirm="-y"
             else
@@ -130,7 +137,7 @@ case "${1}" in
         ;;
     enable|disable|lock|unlock|launch)
         sub_cmd="$1"
-        pkg_id=$(trim_pkg_id "$2")
+        pkg_id=${2%/}
         metapkg_dir=$(get_metapkg_dir $pkg_id)
         shift && shift
         ${metapkg_dir}/${pkg_id}.sh $sub_cmd $@
